# Site
name: "KorGE Game Engine"
title: "KorGE Game Engine"
description: "Kotlin Multiplatform Game Engine"
meta_description: "Kotlin Multiplatform Game Engine."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
#baseurl: '.'
email: 'soywiz@gmail.com'
google_analytics: 'G-WC3WXWPQSR'
disqus: 'korgegameengine'

# Authors
authors:
  soywiz:
    name: Carlos Ballesteros Velasco
    display_name: soywiz
    gravatar: 52a7e0168b945855f23900c0a8da7787
    email: soywiz@gmail.com
    web: https://soywiz.com/
    twitter: https://twitter.com/cballesterosvel
    description: "Author of KorGE."
  rezmike:
    name: Mikhail Reznichenko
    display_name: rezmike
    gravatar: ""
    email: ""
    web: https://github.com/RezMike
    twitter: ""
    description: ""
  nico:
    name: Nicolai Emig
    display_name: emign
    gravatar: ""
    email: ""
    web: https://github.com/emign
    twitter: ""
    description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

collections:
  category:
    output: true
    permalink: /:collection/:name

# Other
markdown: kramdown
highlighter: rouge
#permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:title
